
BLOCK_INTERVAL_SECONDS = 30

NETWORK_SPREADING_SECONDS = 60 # 10 minutes in real world
MAX_MESSAGE_DELAY_SECONDS = NETWORK_SPREADING_SECONDS * 6
FROZEN_BLOCK_NO = 100

NEIGHBOURHOODS_HOPS = 2

LEADERS_NUM = 4
# ELECTION_WAIT = 2

BOOTSTRAP_BY_PORT_NO = True

NODE_DIVISION = True
