
BLOCK_INTERVAL_SECONDS = 60
BLOCK_DIFFICULTY_CYCLE = 12

NETWORK_SPREADING_SECONDS = 60 # 10 minutes in real world
MAX_MESSAGE_DELAY_SECONDS = 0 #NETWORK_SPREADING_SECONDS * 6
FROZEN_BLOCK_NO = 100

NEIGHBOURHOODS_HOPS = 2

LEADERS_NUM = 4
# ELECTION_WAIT = 2
MINING = True

BOOTSTRAP_BY_PORT_NO = True

NODE_DIVISION = True
